CREATE TABLE IF NOT EXISTS Classes(cID int NOT NULL PRIMARY KEY, cName varchar(10) NOT NULL);

INSERT INTO Classes VALUES (1,"CS147");
INSERT INTO Classes VALUES (2,"CS221");
INSERT INTO Classes VALUES (3,"E40");
INSERT INTO Classes VALUES (4,"MATH51");
INSERT INTO Classes VALUES (5,"CS145");
INSERT INTO Classes VALUES (6,"ECON137");
INSERT INTO Classes VALUES (7,"ECON1A");
INSERT INTO Classes VALUES (8,"CS106A");
INSERT INTO Classes VALUES (9,"HUMBIO2A");
INSERT INTO Classes VALUES (10,"STS101");