CREATE TABLE IF NOT EXISTS Favorites( uID int NOT NULL, fID int NOT NULL, PRIMARY KEY (uID, fID)); 

INSERT INTO Favorites VALUES (1,2);
INSERT INTO Favorites VALUES (1,3);
INSERT INTO Favorites VALUES (2,1);
INSERT INTO Favorites VALUES (3,1);
INSERT INTO Favorites VALUES (3,2);